# configs/nuscenes_front_7cls.yaml
eps: 0.001
eval_mode: False
use_diffmot: False

lr: 0.0001

data_dir: "./data/nuscenes_tracks/train"
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 300
batch_size: 1024          # se OOM, scendi a 512/256
seed: 123
eval_every: 10
gpus: [0]
preprocess_workers: 8

# (test lo metteremo dopo)
eval_at: 300
det_dir: ""
info_dir: ""
reid_dir: ""
save_dir: "./results/nuscenes_front_ft"
eval_expname: nuscenes_front_ft
show_image: False
use_detection_model: False
high_thres: 0.6
low_thres: 0.1
w_assoc_emb: 2.2
aw_param: 1.7

device: cuda
eval_device: None
