# =======================
# Eval Config - nuScenes
# =======================
eps: 0.001
eval_mode: True
use_diffmot: False

# optimizer (non usato in eval, ma richiesto)
lr: 0.0001
batch_size: 1

# dirs
data_dir: "./data/nuscenes_tracks/train"
det_dir: "./data/nuscenes_mot_front/detections/val"
info_dir: "./data/nuscenes_mot_front/val"
reid_dir: "./cache/embeddings"
save_dir: "./results/nuscenes_front_eval"
weight_path: "./experiments/nuscenes_front_ft/nuscenes_epoch150.pt"
diffnet: HMINet

# model & test params
interval: 5
augment: False
encoder_dim: 256
tf_layer: 3
eval_at: 150      
high_thres: 0.6
low_thres: 0.1
w_assoc_emb: 2.2
aw_param: 1.7
gpus: [0]
device: cuda
eval_device: None
preprocess_workers: 8

eval_expname: nuscenes_front_eval
show_image: False
use_detection_model: False
